# Generated by Django 6.0.4 on 2026-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
